/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package insurance.management.system;

import common.OpenPDF;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import common.OpenPDF;
import dao.Insurance_AppUser_dao;
import dao.Insurance_Policy_Bill_Details_dao;
import dao.Insurance_Policy_Bill_dao;
import dao.Insurance_Policy_dao;
import dao.Insurance_dao;
import java.io.FileOutputStream;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import model.Insurance;
import model.Insurance_Policy;
import model.Insurance_Policy_Bill;
import model.Insurance_Policy_Bill_Details;
import model.User;

/**
 *
 * @author nidsp
 */
public class BuyPolicy extends javax.swing.JFrame {
    public int billId;
    public int totalAmount = 0;
    public int policySumAssured = 0;
    public int policyPremium = 0;
    public int policyTenure = 0;
    public String userEmail;

    /**
     * Creates new form BuyPolicy
     */
    public BuyPolicy() {
        initComponents();
    }
    
    public BuyPolicy(String email) {
        initComponents();
        txtName.setEditable(false);
        txtMobileNumber.setEditable(false);
        txtEmail.setEditable(false);
        txtPolicyName.setEditable(false);
        txtPolicySumAssured.setEditable(false);
        txtPolicyPremium.setEditable(false);
        txtPolicyTenure.setEditable(false);
        txtPolicyDescriptions.setEditable(false);
        btnAddToCart.setEnabled(false);
        btnGenerateBill.setEnabled(false);
        userEmail = email;
        
    }
    
    public void policyNameByCategory(String insuranceType) {
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        dtm.setRowCount(0);
        ArrayList<Insurance_Policy> list = Insurance_Policy_dao.getAllRecordsByInsurance (insuranceType);
        Iterator<Insurance_Policy> itr = list.iterator();
        while(itr.hasNext()) {
            Insurance_Policy insurancePolicyObj = itr.next();
            dtm.addRow(new Object[] {insurancePolicyObj.getName()});
        }
    }
    
    public void filterPolicyByName(String name, String insuranceType) {
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        dtm.setRowCount(0);
        ArrayList<Insurance_Policy> list = Insurance_Policy_dao.filterInsurancePolicyByName(name,insuranceType);
        Iterator<Insurance_Policy> itr = list.iterator();
        while (itr.hasNext()) {
            Insurance_Policy insurancePolicyObj = itr.next();
            dtm.addRow(new Object[]{insurancePolicyObj.getName()});
        }
    }
    
    public void clearPolicyFields() {
        txtPolicyName.setText("");
        txtPolicySumAssured.setText("");
        txtPolicyPremium.setText("");
        txtPolicyTenure.setText("");
        txtPolicyDescriptions.setText("");
        btnAddToCart.setEnabled(false);
    }
    
    public void validateFields () {
        if(totalAmount>0) {
            btnGenerateBill.setEnabled(true);
        }
        else {
            btnGenerateBill.setEnabled(false);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnClose = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtMobileNumber = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtInsuranceComboBox = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        txtPolicyName = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtPolicySumAssured = new javax.swing.JTextField();
        txtPolicyPremium = new javax.swing.JTextField();
        txtPolicyTenure = new javax.swing.JTextField();
        txtPolicyDescriptions = new javax.swing.JTextField();
        btnClear = new javax.swing.JButton();
        btnAddToCart = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        lblTotalAmount = new javax.swing.JLabel();
        btnGenerateBill = new javax.swing.JButton();
        lblBillId = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/place order.png"))); // NOI18N
        jLabel1.setText("Buy Policy");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(495, 6, -1, -1));

        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close.png"))); // NOI18N
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        getContentPane().add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(1218, 24, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Bill Id : ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Customer Details");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Name");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        txtName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 250, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Mobile Number");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        txtMobileNumber.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(txtMobileNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 250, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Email");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

        txtEmail.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 250, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Insurance");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 70, -1, -1));

        txtInsuranceComboBox.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtInsuranceComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInsuranceComboBoxActionPerformed(evt);
            }
        });
        getContentPane().add(txtInsuranceComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 70, 251, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Search");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, -1, -1));

        txtSearch.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });
        getContentPane().add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 120, 251, -1));

        jTable1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, 373, 200));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Name");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 70, -1, -1));

        txtPolicyName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(txtPolicyName, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 70, 250, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Sum Assured");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 110, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Premium");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 160, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Tenure");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 210, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Description");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 260, -1, -1));

        txtPolicySumAssured.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(txtPolicySumAssured, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 110, 250, -1));

        txtPolicyPremium.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(txtPolicyPremium, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 160, 250, -1));

        txtPolicyTenure.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(txtPolicyTenure, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 210, 250, -1));

        txtPolicyDescriptions.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(txtPolicyDescriptions, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 260, 250, -1));

        btnClear.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clear.png"))); // NOI18N
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        getContentPane().add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 110, -1, 37));

        btnAddToCart.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAddToCart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add to cart.png"))); // NOI18N
        btnAddToCart.setText("Add To Cart");
        btnAddToCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddToCartActionPerformed(evt);
            }
        });
        getContentPane().add(btnAddToCart, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 190, -1, 37));

        jTable2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Insurance Type", "Sum Assured", "Premium", "Tenure", "Description"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 1220, 290));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Total Premium Amount Rs.");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 670, -1, -1));

        lblTotalAmount.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTotalAmount.setText("000");
        getContentPane().add(lblTotalAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 670, -1, -1));

        btnGenerateBill.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnGenerateBill.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/generate bill & print.png"))); // NOI18N
        btnGenerateBill.setText("Generate Bill & Print");
        btnGenerateBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerateBillActionPerformed(evt);
            }
        });
        getContentPane().add(btnGenerateBill, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 670, -1, 30));

        lblBillId.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(lblBillId, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 60, 67, 22));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/all_pages_background.png"))); // NOI18N
        jLabel16.setMaximumSize(new java.awt.Dimension(1280, 768));
        jLabel16.setMinimumSize(new java.awt.Dimension(1280, 768));
        jLabel16.setPreferredSize(new java.awt.Dimension(1280, 768));
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 768));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new Home(userEmail).setVisible(true);
    }//GEN-LAST:event_btnCloseActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        billId = Integer.parseInt(Insurance_Policy_Bill_dao.getId());
        lblBillId.setText(Insurance_Policy_Bill_dao.getId());
        
        User user = Insurance_AppUser_dao.getUserDetails(userEmail);
        txtName.setText(user.getName());
        txtMobileNumber.setText(user.getMobileNumber());
        txtEmail.setText(user.getEmail());
        
        ArrayList<Insurance> list = Insurance_dao.getAllRecords();
        Iterator<Insurance> itr = list.iterator();
        while(itr.hasNext()) {
            Insurance insuranceObj = itr.next();
            txtInsuranceComboBox.addItem(insuranceObj.getName());
        }
        String insurance = (String) txtInsuranceComboBox.getSelectedItem();
        policyNameByCategory(insurance);
    }//GEN-LAST:event_formComponentShown

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        // TODO add your handling code here:
        String name = txtSearch.getText();
        String insurance = (String) txtInsuranceComboBox.getSelectedItem();
        filterPolicyByName(name,insurance);
    }//GEN-LAST:event_txtSearchKeyReleased

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int index = jTable1.getSelectedRow();
        TableModel model = jTable1.getModel();
        String policyName = model.getValueAt(index,0).toString();
        Insurance_Policy insurance_policy = Insurance_Policy_dao.getInsurancePolicyByName(policyName);
        txtPolicyName.setText(insurance_policy.getName());
        txtPolicySumAssured.setText(insurance_policy.getSumAssured());
        txtPolicyPremium.setText(insurance_policy.getPremium());
        txtPolicyTenure.setText(insurance_policy.getTenure());
        txtPolicyDescriptions.setText(insurance_policy.getDescriptions());
        btnAddToCart.setEnabled(true);
    }//GEN-LAST:event_jTable1MouseClicked

    private void txtInsuranceComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInsuranceComboBoxActionPerformed
        // TODO add your handling code here:
        String insurance = (String) txtInsuranceComboBox.getSelectedItem();
        policyNameByCategory(insurance);
    }//GEN-LAST:event_txtInsuranceComboBoxActionPerformed

    private void btnAddToCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddToCartActionPerformed
        // TODO add your handling code here:
        String name = txtPolicyName.getText();
        String insurance = (String) txtInsuranceComboBox.getSelectedItem();
        String sumAssured = txtPolicySumAssured.getText();
        String premium = txtPolicyPremium.getText();
        String tenure = txtPolicyTenure.getText();
        String descriptions = txtPolicyDescriptions.getText();
        int premiums = Integer.parseInt(premium);
        
        DefaultTableModel dtm = (DefaultTableModel) jTable2.getModel();
        dtm.addRow(new Object[] {name,insurance,sumAssured,premiums,tenure,descriptions});
        
        totalAmount = totalAmount + premiums;
        lblTotalAmount.setText(String.valueOf(totalAmount));
        
        clearPolicyFields();
        validateFields();
        
    }//GEN-LAST:event_btnAddToCartActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        clearPolicyFields();
        
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnGenerateBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateBillActionPerformed
        // TODO add your handling code here:
        String name = txtName.getText();
        String email = txtEmail.getText();
        SimpleDateFormat dFormat = new SimpleDateFormat("dd-MM-yyyy");
        Date date = new Date();
        String todaydate = dFormat.format(date);
        String total = String.valueOf(totalAmount);
        
        User user = Insurance_AppUser_dao.getUserDetails(userEmail);
        
        Insurance_Policy_Bill insurance_policy_bill = new Insurance_Policy_Bill();
        
        insurance_policy_bill.setId(billId);
        insurance_policy_bill.setCustomerId(user.getId());
        insurance_policy_bill.setBillDate(todaydate);
        insurance_policy_bill.setTotalAmount(total);
        
        Insurance_Policy_Bill_dao.save(insurance_policy_bill); 
     
        for (int i = 0; i < jTable2.getRowCount(); i++) {
            Insurance_Policy_Bill_Details insurance_policy_bill_details = new Insurance_Policy_Bill_Details();
            insurance_policy_bill_details.setBillId(billId);
            Integer Id = Insurance_Policy_dao.getId(jTable2.getValueAt(i, 0).toString());
            insurance_policy_bill_details.setPolicyId(Id);
            Insurance_Policy_Bill_Details_dao.save(insurance_policy_bill_details);
        }

        //Create Document
        String path = "C:\\Users\\nidsp\\OneDrive - Illinois Institute of Technology\\Documents\\Project Stuff\\Path for Saving Document\\Bill Number ";
        com.itextpdf.text.Document doc = new com.itextpdf.text.Document();
        try {
            PdfWriter.getInstance(doc, new FileOutputStream(path + "" + billId + ".pdf"));
            doc.open();
            Paragraph insuranceCompanyName = new Paragraph("                                                 Insurance Management Company\n");
            doc.add(insuranceCompanyName);
            Paragraph starLine = new Paragraph("**************************************************************************************************************");
            doc.add(starLine);
            Paragraph paragraph3 = new Paragraph("\tBill ID:"+billId+"\nCustomer Name: "+name+"\nTotal Paid: "+totalAmount);
            doc.add(paragraph3);
            doc.add(starLine);
            PdfPTable tb1 = new PdfPTable(6);
            tb1.addCell("Name");
            tb1.addCell("Insurance Type");
            tb1.addCell("Sum Assured");
            tb1.addCell("Premium");
            tb1.addCell("Tenure");
            tb1.addCell("Description");

            for (int i=0; i<jTable2.getRowCount(); i++) {
                String n0 = jTable2.getValueAt(i, 0).toString();
                String n1 = jTable2.getValueAt(i, 1).toString();
                String n2 = jTable2.getValueAt(i, 2).toString();
                String n3 = jTable2.getValueAt(i, 3).toString();
                String n4 = jTable2.getValueAt(i, 4).toString();
                String n5 = jTable2.getValueAt(i, 5).toString();
                tb1.addCell(n0);
                tb1.addCell(n1);
                tb1.addCell(n2);
                tb1.addCell(n3);
                tb1.addCell(n4);
                tb1.addCell(n5);
            }
            
            doc.add(tb1);
            doc.add(starLine);
            Paragraph thanksMsg = new Paragraph("Thank You");
            doc.add(thanksMsg);
            
            //Open PDF
            OpenPDF.openById(String.valueOf(billId));
        }
        catch(Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
        doc.close();
        setVisible(false);
        new Home(email).setVisible(true);
    }//GEN-LAST:event_btnGenerateBillActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:
        int index = jTable2.getSelectedRow();
        int a = JOptionPane.showConfirmDialog(null, "Do you want to remove this policy?","Select",JOptionPane.YES_NO_OPTION);
        if(a==0) {
            TableModel model = jTable2.getModel();
            String total = model.getValueAt(index, 3).toString();
            totalAmount = totalAmount - Integer.parseInt(total);
            lblTotalAmount.setText(String.valueOf(totalAmount));
            ((DefaultTableModel) jTable2.getModel()).removeRow(index);
        }
    }//GEN-LAST:event_jTable2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuyPolicy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuyPolicy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuyPolicy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuyPolicy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BuyPolicy().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddToCart;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnGenerateBill;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel lblBillId;
    private javax.swing.JLabel lblTotalAmount;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JComboBox<String> txtInsuranceComboBox;
    private javax.swing.JTextField txtMobileNumber;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPolicyDescriptions;
    private javax.swing.JTextField txtPolicyName;
    private javax.swing.JTextField txtPolicyPremium;
    private javax.swing.JTextField txtPolicySumAssured;
    private javax.swing.JTextField txtPolicyTenure;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
