/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package insurance.management.system;

import javax.swing.JOptionPane;

/**
 *
 * @author nidsp
 */
public class Home extends javax.swing.JFrame {
    public String email;

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }
    
    public Home(String userEmail) {
        initComponents();
        email = userEmail;
        if(!email.equals("admin@gmail.com")) {
            btnManageInsurance.setVisible(false);
            btnNewPolicy.setVisible(false);
            btnViewEditAndDeletePolicy.setVisible(false);
            btnVerifyUsers.setVisible(false);
            btnInsightsDashboard.setVisible(false);
            btnSoldPolicies.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnLogout = new javax.swing.JButton();
        btnBuyPolicy = new javax.swing.JButton();
        btnViewPolicyBillDetails = new javax.swing.JButton();
        btnChangePassword = new javax.swing.JButton();
        btnChangeSecurityQuestion = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        btnManageInsurance = new javax.swing.JButton();
        btnNewPolicy = new javax.swing.JButton();
        btnViewEditAndDeletePolicy = new javax.swing.JButton();
        btnVerifyUsers = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnInsightsDashboard = new javax.swing.JButton();
        btnSoldPolicies = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1280, 768));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnLogout.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logout.png"))); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 139, 350, 70));

        btnBuyPolicy.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnBuyPolicy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/place order.png"))); // NOI18N
        btnBuyPolicy.setText("Buy Policy");
        btnBuyPolicy.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnBuyPolicy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuyPolicyActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuyPolicy, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, 350, 70));

        btnViewPolicyBillDetails.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnViewPolicyBillDetails.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/viewBillOrderPlacedDetails.png"))); // NOI18N
        btnViewPolicyBillDetails.setText("View Policy Bill Details");
        btnViewPolicyBillDetails.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnViewPolicyBillDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewPolicyBillDetailsActionPerformed(evt);
            }
        });
        getContentPane().add(btnViewPolicyBillDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 340, 350, 70));

        btnChangePassword.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnChangePassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/change Password.png"))); // NOI18N
        btnChangePassword.setText("Change Password");
        btnChangePassword.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnChangePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangePasswordActionPerformed(evt);
            }
        });
        getContentPane().add(btnChangePassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(673, 139, 350, 70));

        btnChangeSecurityQuestion.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnChangeSecurityQuestion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/change Security Question.png"))); // NOI18N
        btnChangeSecurityQuestion.setText("Change Security Question");
        btnChangeSecurityQuestion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnChangeSecurityQuestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeSecurityQuestionActionPerformed(evt);
            }
        });
        getContentPane().add(btnChangeSecurityQuestion, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 240, 350, 70));

        btnExit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit small.png"))); // NOI18N
        btnExit.setText("Exit");
        btnExit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 340, 350, 70));

        btnManageInsurance.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnManageInsurance.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/category.png"))); // NOI18N
        btnManageInsurance.setText("Manage Insurance");
        btnManageInsurance.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnManageInsurance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageInsuranceActionPerformed(evt);
            }
        });
        getContentPane().add(btnManageInsurance, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 430, 350, 80));

        btnNewPolicy.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnNewPolicy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/new product.png"))); // NOI18N
        btnNewPolicy.setText("New Policy");
        btnNewPolicy.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnNewPolicy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewPolicyActionPerformed(evt);
            }
        });
        getContentPane().add(btnNewPolicy, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 530, 350, 70));

        btnViewEditAndDeletePolicy.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnViewEditAndDeletePolicy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/view edit delete product.png"))); // NOI18N
        btnViewEditAndDeletePolicy.setText("View, Edit & Delete Policy");
        btnViewEditAndDeletePolicy.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnViewEditAndDeletePolicy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewEditAndDeletePolicyActionPerformed(evt);
            }
        });
        getContentPane().add(btnViewEditAndDeletePolicy, new org.netbeans.lib.awtextra.AbsoluteConstraints(676, 427, 350, 80));

        btnVerifyUsers.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnVerifyUsers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/verify users.png"))); // NOI18N
        btnVerifyUsers.setText("Verify Users");
        btnVerifyUsers.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnVerifyUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerifyUsersActionPerformed(evt);
            }
        });
        getContentPane().add(btnVerifyUsers, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 530, 340, 70));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setText("Dashboard");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(522, 19, -1, -1));

        btnInsightsDashboard.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnInsightsDashboard.setText("Insights Dashboard");
        btnInsightsDashboard.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnInsightsDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsightsDashboardActionPerformed(evt);
            }
        });
        getContentPane().add(btnInsightsDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 630, 350, 70));

        btnSoldPolicies.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnSoldPolicies.setText("View Sold Policies");
        btnSoldPolicies.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnSoldPolicies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSoldPoliciesActionPerformed(evt);
            }
        });
        getContentPane().add(btnSoldPolicies, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 630, 350, 70));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/all_pages_background.png"))); // NOI18N
        jLabel2.setMaximumSize(new java.awt.Dimension(1280, 768));
        jLabel2.setMinimumSize(new java.awt.Dimension(1280, 768));
        jLabel2.setPreferredSize(new java.awt.Dimension(1280, 768));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 768));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null,"Do you really want to Logout?","Select",JOptionPane.YES_NO_OPTION);
        if (a==0) {
            setVisible(false);
            new Login().setVisible(true);
        }
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null,"Do you really want to Close Application?","Select",JOptionPane.YES_NO_OPTION);
        if (a==0) {
            System.exit(0);
        }
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnManageInsuranceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageInsuranceActionPerformed
        // TODO add your handling code here:
        new ManageInsurance().setVisible(true);
    }//GEN-LAST:event_btnManageInsuranceActionPerformed

    private void btnNewPolicyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewPolicyActionPerformed
        // TODO add your handling code here:
        new NewPolicy().setVisible(true);
    }//GEN-LAST:event_btnNewPolicyActionPerformed

    private void btnViewEditAndDeletePolicyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewEditAndDeletePolicyActionPerformed
        // TODO add your handling code here:
        new ViewEditDeletePolicy().setVisible(true);
    }//GEN-LAST:event_btnViewEditAndDeletePolicyActionPerformed

    private void btnVerifyUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerifyUsersActionPerformed
        // TODO add your handling code here:
        new VerifyUser().setVisible(true);
    }//GEN-LAST:event_btnVerifyUsersActionPerformed

    private void btnBuyPolicyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuyPolicyActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new BuyPolicy(email).setVisible(true);
    }//GEN-LAST:event_btnBuyPolicyActionPerformed

    private void btnViewPolicyBillDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewPolicyBillDetailsActionPerformed
        // TODO add your handling code here:
        new ViewPolicyBillDetails(email).setVisible(true);
    }//GEN-LAST:event_btnViewPolicyBillDetailsActionPerformed

    private void btnChangePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangePasswordActionPerformed
        // TODO add your handling code here:
        new ChangePassword(email).setVisible(true);
    }//GEN-LAST:event_btnChangePasswordActionPerformed

    private void btnChangeSecurityQuestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeSecurityQuestionActionPerformed
        // TODO add your handling code here:
        new ChangeSecurityQuestion(email).setVisible(true);
    }//GEN-LAST:event_btnChangeSecurityQuestionActionPerformed

    private void btnInsightsDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsightsDashboardActionPerformed
        // TODO add your handling code here:
        new Insights(email).setVisible(true);
    }//GEN-LAST:event_btnInsightsDashboardActionPerformed

    private void btnSoldPoliciesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSoldPoliciesActionPerformed
        // TODO add your handling code here:
        new ViewSoldPolicyDetails(email).setVisible(true);
    }//GEN-LAST:event_btnSoldPoliciesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuyPolicy;
    private javax.swing.JButton btnChangePassword;
    private javax.swing.JButton btnChangeSecurityQuestion;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnInsightsDashboard;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnManageInsurance;
    private javax.swing.JButton btnNewPolicy;
    private javax.swing.JButton btnSoldPolicies;
    private javax.swing.JButton btnVerifyUsers;
    private javax.swing.JButton btnViewEditAndDeletePolicy;
    private javax.swing.JButton btnViewPolicyBillDetails;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
