/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package insurance.management.system;

import java.util.ArrayList;
import java.util.Iterator;
import model.Insurance;
import model.Insurance_Policy;
import dao.Insurance_dao;
import dao.Insurance_Policy_dao;
/**
 *
 * @author nidsp
 */
public class NewPolicy extends javax.swing.JFrame {

    /**
     * Creates new form NewPolicy
     */
    public NewPolicy() {
        initComponents();
        btnSave.setEnabled(false);
    }
    
    public void validateFields () {
        String name = txtName.getText();
        String sumAssured = txtSumAssured.getText();
        String premium = txtPremium.getText();
        String tenure = txtTenure.getText();
        String descriptions = txtDescriptions.getText();
        
        if(!name.equals("") &&
           !sumAssured.equals("") &&
           !premium.equals("") &&
           !tenure.equals("") &&
           !descriptions.equals("")) {
            btnSave.setEnabled(true);
        }
        else {
            btnSave.setEnabled(false);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnClose = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtSumAssured = new javax.swing.JTextField();
        txtInsuranceType = new javax.swing.JComboBox<>();
        btnSave = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtPremium = new javax.swing.JTextField();
        txtTenure = new javax.swing.JTextField();
        txtDescriptions = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/new product.png"))); // NOI18N
        jLabel1.setText("New Policy");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(491, 6, -1, -1));

        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close.png"))); // NOI18N
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        getContentPane().add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(1224, 29, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Policy Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 130, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Insurance Type");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 180, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Sum Assurred");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 230, -1, -1));

        txtName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNameKeyReleased(evt);
            }
        });
        getContentPane().add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 130, 350, -1));

        txtSumAssured.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtSumAssured.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSumAssuredKeyReleased(evt);
            }
        });
        getContentPane().add(txtSumAssured, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 230, 350, -1));

        txtInsuranceType.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(txtInsuranceType, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 180, 350, -1));

        btnSave.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save.png"))); // NOI18N
        btnSave.setText("Save");
        btnSave.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 460, 129, 42));

        btnClear.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clear.png"))); // NOI18N
        btnClear.setText("Clear");
        btnClear.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        getContentPane().add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 460, 123, 42));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Premium");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 290, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Tenure");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 340, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Description");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 390, -1, -1));

        txtPremium.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtPremium.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPremiumKeyReleased(evt);
            }
        });
        getContentPane().add(txtPremium, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 290, 350, -1));

        txtTenure.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtTenure.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTenureKeyReleased(evt);
            }
        });
        getContentPane().add(txtTenure, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 340, 350, -1));

        txtDescriptions.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtDescriptions.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDescriptionsKeyReleased(evt);
            }
        });
        getContentPane().add(txtDescriptions, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 390, 350, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/all_pages_background.png"))); // NOI18N
        jLabel8.setMaximumSize(new java.awt.Dimension(1280, 768));
        jLabel8.setMinimumSize(new java.awt.Dimension(1280, 768));
        jLabel8.setPreferredSize(new java.awt.Dimension(1280, 768));
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 768));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNameKeyReleased
        // TODO add your handling code here:
        validateFields();
    }//GEN-LAST:event_txtNameKeyReleased

    private void txtSumAssuredKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSumAssuredKeyReleased
        // TODO add your handling code here:
        validateFields();
    }//GEN-LAST:event_txtSumAssuredKeyReleased

    private void txtPremiumKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPremiumKeyReleased
        // TODO add your handling code here:
        validateFields();
    }//GEN-LAST:event_txtPremiumKeyReleased

    private void txtTenureKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTenureKeyReleased
        // TODO add your handling code here:
        validateFields();
    }//GEN-LAST:event_txtTenureKeyReleased

    private void txtDescriptionsKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescriptionsKeyReleased
        // TODO add your handling code here:
        validateFields();
    }//GEN-LAST:event_txtDescriptionsKeyReleased

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        ArrayList<Insurance> list = Insurance_dao.getAllRecords();
        Iterator<Insurance> itr = list.iterator();
        while(itr.hasNext()) {
            Insurance insuranceObj = itr.next();
            txtInsuranceType.addItem(insuranceObj.getName());
        }
    }//GEN-LAST:event_formComponentShown

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        Insurance insurance = Insurance_dao.getId((String)txtInsuranceType.getSelectedItem());
        Insurance_Policy insurancePolicy = new Insurance_Policy();
        insurancePolicy.setName(txtName.getText());
        insurancePolicy.setInsuranceId(insurance.getId());
        insurancePolicy.setSumAssured(txtSumAssured.getText());
        insurancePolicy.setPremium(txtPremium.getText());
        insurancePolicy.setTenure(txtTenure.getText());
        insurancePolicy.setDescriptions(txtDescriptions.getText());
        Insurance_Policy_dao.save(insurancePolicy);
        setVisible(false);
        new NewPolicy().setVisible(true);
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new NewPolicy().setVisible(true);        
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_btnCloseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewPolicy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewPolicy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewPolicy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewPolicy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewPolicy().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField txtDescriptions;
    private javax.swing.JComboBox<String> txtInsuranceType;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPremium;
    private javax.swing.JTextField txtSumAssured;
    private javax.swing.JTextField txtTenure;
    // End of variables declaration//GEN-END:variables
}
