/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package insurance.management.system;

import dao.Insurance_Policy_List_dao;
import dao.Insurance_Policy_dao;
import dao.Insurance_dao;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import model.Insurance;
import model.Insurance_Policy;
import model.Insurance_Policy_List;

/**
 *
 * @author nidsp
 */
public class ViewEditDeletePolicy extends javax.swing.JFrame {

    /**
     * Creates new form ViewEditDeletePolicy
     */
    public ViewEditDeletePolicy() {
        initComponents();
        btnUpdate.setEnabled(false);
        btnDelete.setEnabled(false);
    }
    
    public void validateFields() {
        String name = txtName.getText();
        String insuranceType = (String) txtInsuranceType.getSelectedItem();
        String sumAssured = txtSumAssured.getText();
        String premium = txtPremium.getText();
        String tenure = txtTenure.getText();
        String descriptions = txtDescriptions.getText();
        
        if(!name.equals("") &&
           !insuranceType.equals("") &&
           !sumAssured.equals("") &&
           !premium.equals("") &&
           !tenure.equals("") &&
           !descriptions.equals("")) {
            btnUpdate.setEnabled(true);
        }
        else {
            btnUpdate.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnClose = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtSumAssured = new javax.swing.JTextField();
        txtPremium = new javax.swing.JTextField();
        txtTenure = new javax.swing.JTextField();
        txtDescriptions = new javax.swing.JTextField();
        txtInsuranceType = new javax.swing.JComboBox<>();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        txtId = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/view edit delete product.png"))); // NOI18N
        jLabel1.setText("View, Edit & Delete Policy");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, 24, -1, -1));

        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close.png"))); // NOI18N
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        getContentPane().add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(1222, 24, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 239, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Insurance Type");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 303, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Sum Assured");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 360, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Premium");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 423, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Tenure");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 486, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Description");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 543, -1, -1));

        txtName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNameKeyReleased(evt);
            }
        });
        getContentPane().add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(286, 236, 291, -1));

        txtSumAssured.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtSumAssured.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSumAssuredKeyReleased(evt);
            }
        });
        getContentPane().add(txtSumAssured, new org.netbeans.lib.awtextra.AbsoluteConstraints(286, 357, 291, -1));

        txtPremium.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtPremium.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPremiumKeyReleased(evt);
            }
        });
        getContentPane().add(txtPremium, new org.netbeans.lib.awtextra.AbsoluteConstraints(286, 420, 291, -1));

        txtTenure.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtTenure.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTenureKeyReleased(evt);
            }
        });
        getContentPane().add(txtTenure, new org.netbeans.lib.awtextra.AbsoluteConstraints(286, 483, 291, -1));

        txtDescriptions.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtDescriptions.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDescriptionsKeyReleased(evt);
            }
        });
        getContentPane().add(txtDescriptions, new org.netbeans.lib.awtextra.AbsoluteConstraints(286, 540, 291, -1));

        txtInsuranceType.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(txtInsuranceType, new org.netbeans.lib.awtextra.AbsoluteConstraints(286, 300, 291, -1));

        btnUpdate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save.png"))); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        getContentPane().add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 608, -1, 43));

        btnDelete.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete.png"))); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(304, 608, -1, 43));

        btnClear.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clear.png"))); // NOI18N
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        getContentPane().add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 608, 117, 43));

        jTable1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Insurance Type", "Sum Assured", "Premium", "Tenure", "Description"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(595, 183, 636, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/all_pages_background.png"))); // NOI18N
        jLabel10.setMaximumSize(new java.awt.Dimension(1280, 768));
        jLabel10.setMinimumSize(new java.awt.Dimension(1280, 768));
        jLabel10.setPreferredSize(new java.awt.Dimension(1280, 768));
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 768));
        getContentPane().add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNameKeyReleased
        // TODO add your handling code here:
        validateFields();
    }//GEN-LAST:event_txtNameKeyReleased

    private void txtSumAssuredKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSumAssuredKeyReleased
        // TODO add your handling code here:
        validateFields();
    }//GEN-LAST:event_txtSumAssuredKeyReleased

    private void txtPremiumKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPremiumKeyReleased
        // TODO add your handling code here:
        validateFields();
    }//GEN-LAST:event_txtPremiumKeyReleased

    private void txtTenureKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTenureKeyReleased
        // TODO add your handling code here:
        validateFields();
    }//GEN-LAST:event_txtTenureKeyReleased

    private void txtDescriptionsKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescriptionsKeyReleased
        // TODO add your handling code here:
        validateFields();
    }//GEN-LAST:event_txtDescriptionsKeyReleased

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        Insurance insurance = Insurance_dao.getId((String)txtInsuranceType.getSelectedItem());
        Integer PolicyId = Integer.parseInt(txtId.getText());
        String Policyname = txtName.getText();
        Integer insuranceId = (Integer) insurance.getId();
        String sumAssured = txtSumAssured.getText();
        String premium = txtPremium.getText();
        String tenure = txtTenure.getText();
        String descriptions = txtDescriptions.getText();
        
        Insurance_Policy_dao.update(PolicyId,Policyname,insuranceId,sumAssured,premium,tenure,descriptions);
        setVisible(false);
        new ViewEditDeletePolicy().setVisible(true);
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        ArrayList<Insurance_Policy_List> list = Insurance_Policy_List_dao.getAllRecords();
        Iterator<Insurance_Policy_List> itr = list.iterator();
        while(itr.hasNext()) {
            Insurance_Policy_List insurancePolicyListObj = itr.next();
            dtm.addRow(new Object[] {insurancePolicyListObj.getName(),
            insurancePolicyListObj.getInsuranceType(),insurancePolicyListObj.getSumAssured(),
            insurancePolicyListObj.getPremium(),insurancePolicyListObj.getTenure(),
            insurancePolicyListObj.getDescriptions()});
        }
    }//GEN-LAST:event_formComponentShown

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int index = jTable1.getSelectedRow();
        TableModel model = jTable1.getModel();
        
        
        
        Integer Id = Insurance_Policy_dao.getId(model.getValueAt(index, 0).toString());
        txtId.setText(Id.toString());
        String name = model.getValueAt(index, 0).toString();
        txtName.setText(name);
        String sumAssured = model.getValueAt(index, 2).toString();
        txtSumAssured.setText(sumAssured);
        String premium = model.getValueAt(index, 3).toString();
        txtPremium.setText(premium);
        String tenure = model.getValueAt(index, 4).toString();
        txtTenure.setText(tenure);
        String descriptions = model.getValueAt(index, 5).toString();
        txtDescriptions.setText(descriptions);
        
        String insuranceType = model.getValueAt(index, 1).toString();
        
        btnUpdate.setEnabled(true);
        btnDelete.setEnabled(true);
        
        txtInsuranceType.removeAllItems();
        txtInsuranceType.addItem(insuranceType);
        ArrayList<Insurance> insuranceList = Insurance_dao.getAllRecords();
        Iterator<Insurance> insuranceItr = insuranceList.iterator();
        while(insuranceItr.hasNext()) {
            Insurance insuranceObj = insuranceItr.next();
            if(!insuranceObj.getName().equals(insuranceType)) {
                txtInsuranceType.addItem(insuranceObj.getName());
            }
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        Integer PolicyId = Integer.parseInt(txtId.getText());
        
        int a = JOptionPane.showConfirmDialog(null,"Do you want to Delete this Policy","Select",JOptionPane.YES_NO_OPTION);
        if (a==0) {
            Insurance_Policy_dao.delete(PolicyId);
            setVisible(false);
            new ViewEditDeletePolicy().setVisible(true);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new ViewEditDeletePolicy().setVisible(true);
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_btnCloseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewEditDeletePolicy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewEditDeletePolicy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewEditDeletePolicy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewEditDeletePolicy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewEditDeletePolicy().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtDescriptions;
    private javax.swing.JLabel txtId;
    private javax.swing.JComboBox<String> txtInsuranceType;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPremium;
    private javax.swing.JTextField txtSumAssured;
    private javax.swing.JTextField txtTenure;
    // End of variables declaration//GEN-END:variables
}
