/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package insurance.management.system;

import common.OpenPDF;
import dao.Insurance_Policy_Bill_Details_dao;
import dao.Insurance_Policy_Customer_Bill_dao;
import dao.Insurance_Policy_List_dao;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import model.Insurance_Policy_Customer_Bill;
import model.Insurance_Policy_List;

/**
 *
 * @author nidsp
 */
public class ViewPolicyBillDetails extends javax.swing.JFrame {
    public String userEmail;

    /**
     * Creates new form ViewBillsOrderBuyedPolicy
     */
    public ViewPolicyBillDetails() {
        initComponents();
        SimpleDateFormat dFormat = new SimpleDateFormat("dd-MM-yyyy");
        Date date = new Date();
        String todaydate = dFormat.format(date);
        txtFilter.setText(todaydate);
    }
    
    public ViewPolicyBillDetails(String email) {
        initComponents();
        userEmail = email;
    }
    
    public void tableDetails() {
        String date = txtFilter.getText();
        String incDesc = (String) changeOrderComboBox.getSelectedItem();
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        dtm.setRowCount(0);
        if(incDesc.equals("INC")) {
            ArrayList<Insurance_Policy_Customer_Bill> list = Insurance_Policy_Customer_Bill_dao.getAllRecordsByInc(date,userEmail);
            Iterator<Insurance_Policy_Customer_Bill> itr = list.iterator();
            while(itr.hasNext()) {
                Insurance_Policy_Customer_Bill insurancePolicyCustomerBillObj = itr.next();
                dtm.addRow(new Object[] {insurancePolicyCustomerBillObj.getId(),insurancePolicyCustomerBillObj.getName(),
                insurancePolicyCustomerBillObj.getMobileNumber(),insurancePolicyCustomerBillObj.getEmail(),
                insurancePolicyCustomerBillObj.getBillDate(),insurancePolicyCustomerBillObj.getTotalAmount()});
            }
        }
        else {
            ArrayList<Insurance_Policy_Customer_Bill> list = Insurance_Policy_Customer_Bill_dao.getAllRecordsByDesc(date,userEmail);
            Iterator<Insurance_Policy_Customer_Bill> itr = list.iterator();
            while(itr.hasNext()) {
                Insurance_Policy_Customer_Bill insurancePolicyCustomerBillObj = itr.next();
                dtm.addRow(new Object[] {insurancePolicyCustomerBillObj.getId(),insurancePolicyCustomerBillObj.getName(),
                insurancePolicyCustomerBillObj.getMobileNumber(),insurancePolicyCustomerBillObj.getEmail(),
                insurancePolicyCustomerBillObj.getBillDate(),insurancePolicyCustomerBillObj.getTotalAmount()});
            } 
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnClose = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtFilter = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        changeOrderComboBox = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/viewBillOrderPlacedDetails.png"))); // NOI18N
        jLabel1.setText("View Bill & Order Bought Policy");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(349, 15, -1, -1));

        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close.png"))); // NOI18N
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        getContentPane().add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(1227, 26, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Filter by Date");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 108, -1, -1));

        txtFilter.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtFilter.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFilterKeyReleased(evt);
            }
        });
        getContentPane().add(txtFilter, new org.netbeans.lib.awtextra.AbsoluteConstraints(211, 105, 270, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Change Order By ID");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(547, 108, -1, -1));

        changeOrderComboBox.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        changeOrderComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "INC", "DESC" }));
        changeOrderComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeOrderComboBoxActionPerformed(evt);
            }
        });
        getContentPane().add(changeOrderComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(703, 105, 299, -1));

        jTable1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Bill ID", "Name", "Mobile Number", "Email", "Date", "Total"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 161, 1179, 270));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("*Click on Row to View Bill Details");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 640, -1, -1));

        jTable2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Policy Name", "Insurance", "Sum Assured", "Premium", "Tenure", "Description"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 450, 1180, 170));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/all_pages_background.png"))); // NOI18N
        jLabel5.setMaximumSize(new java.awt.Dimension(1280, 768));
        jLabel5.setMinimumSize(new java.awt.Dimension(1280, 768));
        jLabel5.setPreferredSize(new java.awt.Dimension(1280, 768));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 768));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_btnCloseActionPerformed

    private void txtFilterKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFilterKeyReleased
        // TODO add your handling code here:
        tableDetails();
    }//GEN-LAST:event_txtFilterKeyReleased

    private void changeOrderComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeOrderComboBoxActionPerformed
        // TODO add your handling code here:
        tableDetails();
    }//GEN-LAST:event_changeOrderComboBoxActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        DefaultTableModel dtm = (DefaultTableModel) jTable2.getModel();
        dtm.setRowCount(0);
        int index = jTable1.getSelectedRow();
        TableModel model = jTable1.getModel();
        Integer BillId = (Integer) model.getValueAt(index, 0);
        ArrayList<Insurance_Policy_List> list = Insurance_Policy_List_dao.getAllRecordsByBillId(BillId);
        Iterator<Insurance_Policy_List> itr = list.iterator();
        while (itr.hasNext()) {
            Insurance_Policy_List insurancePolicyListObj = itr.next();
            dtm.addRow(new Object[]{insurancePolicyListObj.getName(),
                insurancePolicyListObj.getInsuranceType(), insurancePolicyListObj.getSumAssured(),
                insurancePolicyListObj.getPremium(), insurancePolicyListObj.getTenure(),
                insurancePolicyListObj.getDescriptions()});
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        tableDetails();
    }//GEN-LAST:event_formComponentShown

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewPolicyBillDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewPolicyBillDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewPolicyBillDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewPolicyBillDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewPolicyBillDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JComboBox<String> changeOrderComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField txtFilter;
    // End of variables declaration//GEN-END:variables
}
